#!/bin/bash

############################################################################
#
# This file is part of the ASTERICS Framework.
# 
# Author: Philip Manke <philip.manke@hs-augsburg.de> 2019-07-05
#
######## USAGE #############################################################
#
# This short script starts Automatics into the GUI mode.
#
######## LICENCE ###########################################################
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
############################################################################

if [ -z $ASTERICS_AUTOMATICS_HOME ]; then
    echo "ASTERICS_AUTOMATICS_HOME is not set! Cannot start Automatics!";
    echo "Source the settings.sh file in the root directory of the ASTERICS installation!";
    echo "";
    exit 1;
fi

if [ -z $(which python3) ]; then
    python $ASTERICS_AUTOMATICS_HOME/as_automatics_gui.py;
else
    python3 $ASTERICS_AUTOMATICS_HOME/as_automatics_gui.py;
fi

